config/routes.rb
Wheretomigrate::Application.routes.draw do
  resources :transit_scores

  resources :crimes
  resources :cost_livings
  resources :races
  resources :jobs_cities
  resources :cities do
    collection do
      get 'search'
    end
  end
  resources :counties

  match 'race_bangladeshi' => "Races#race_bangladeshi"
  match 'race_bhutanese' => "Races#race_bhutanese"
  match 'race_burmese' => "Races#race_burmese"
  match 'race_cambodian' => "Races#race_cambodian"
  match 'race_chinese' => "Races#race_chinese"
  match 'race_filipino' => "Races#race_filipino"
  match 'race_hmong' => "Races#race_hmong"
  match 'race_indian' => "Races#race_indian"
  match 'race_indonesian' => "Races#race_indonesian"
  match 'race_japanese' => "Races#race_japanese"
  match 'race_korean' => "Races#race_korean"
  match 'race_laotian' => "Races#race_laotian"
  match 'race_malaysian' => "Races#race_malaysian"

  match 'race_nepalese' => "Races#race_nepalese"
  match 'race_pakistani' => "Races#race_pakistani"
  match 'race_srilankan' => "Races#race_srilankan"
  match 'race_taiwanese' => "Races#race_taiwanese"
  match 'race_thai' => "Races#race_thai"
  match 'race_vietnamese' => "Races#race_vietnamese"
  

  match 'test' => "Home#index"

  root :to => "static_pages#main"

end

app/models/race.rb
class Race < ActiveRecord::Base
  attr_accessible :county_id, :year, :bangladeshi, :bhutanese, :burmese, :cambodian, :chinese, :filipino, :hmong, :indian, :indonesian, :japanese, :korean, :laotian, :malaysian, :nepalese, :pakistani, :srilankan, :taiwanese, :thai, :vietnamese
  belongs_to :county

  # def html
   #{}"<b>"+self.county.name.to_s+"</b><br>"
  #end     
  @number



  def name(name)
    
     @number=self.attributes[name]
  end

  def as_json options={}
    {
      #:lat => self.county.cities.first().latitude, 
      #:lng => self.county.cities.first().longitude,
      :lat => lat,
      :lng => lng,
      :size => @number,
     # :html => 
    }
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController

  def race_bangladeshi
    race("bangladeshi")

  end


  def race_bhutanese
    race("bhutanese")

  end

  def race_burmese
    race("burmese")

  end

  def race_cambodian
    race("cambodian")

  end

  def race_chinese
    race("chinese")

  end

  def race_filipino
    race("filipino")

  end

  def race_hmong
    race("hmong")

  end

  def race_indian
    race("indian")

  end

  def race_indonesian
    race("indonesian")

  end
  def race_japanese
    race("japanese")

  end
  def race_korean
    race("korean")

  end
  def race_laotian
    race("laotian")

  end

  def race_malaysian
    race("malaysian")

  end
  def race_nepalese
    race("nepalese")

  end
  def race_pakistani
    race("pakistani")

  end
 def race_srilankan
    race("srilankan")

  end
 def race_taiwanese
    race("taiwanese")

  end
 def race_thai
    race("thai")

  end


 def race_vietnamese
    race("vietnamese")

  end



  

  # GET /races
  # GET /races.json
  def race(name)
    @races=[]
    Race.all.map do |c|  
      if !c.lat.nil? && !c.lng.nil?

     # if !c.county.nil? && !c.county.cities.nil? && !c.county.cities.first().nil?
                #@races.push({:size => c.name(name), :lat => c.county.cities.first().latitude, :lng => c.county.cities.first().longitude} )

        @races.push({:size => c.name(name), :lat => c.lat, :lng => c.lng} )

        #@races.push({:size => c.name(name), :lat => c.county.name, :lng => c.county.name} )
      end
    end
    #@races = Race.where(["id = ?", 1]).select("county_id,bangladeshi")
    #@races.name()

  

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @races }
    end
  end

  # GET /races
  # GET /races.json
  def index
   @races=Race.all
    #@races = Race.where(["id = ?", 1]).select("county_id,bangladeshi")
    #@races.name()



    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @races }
    end
  end

  # GET /races/1
  # GET /races/1.json
  def show
    @race = Race.find(params[:id]) 

    @race.name(params[:name])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @race }
    end
  end

  # GET /races/new
  # GET /races/new.json
  def new
    @race = Race.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @race }
    end
  end

  # GET /races/1/edit
  def edit
    @race = Race.find(params[:id])
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(params[:race])

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Race was successfully created.' }
        format.json { render json: @race, status: :created, location: @race }
      else
        format.html { render action: "new" }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /races/1
  # PUT /races/1.json
  def update
    @race = Race.find(params[:id])

    respond_to do |format|
      if @race.update_attributes(params[:race])
        format.html { redirect_to @race, notice: 'Race was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race = Race.find(params[:id])
    @race.destroy

    respond_to do |format|
      format.html { redirect_to races_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<%= form_for(@race) do |f| %>
  <% if @race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
      <% @race.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :indian %><br />
    <%= f.number_field :indian %>
  </div>
  <div class="field">
    <%= f.label :bangladeshi %><br />
    <%= f.number_field :bangladeshi %>
  </div>
  <div class="field">
    <%= f.label :bhutanese %><br />
    <%= f.number_field :bhutanese %>
  </div>
  <div class="field">
    <%= f.label :cambodian %><br />
    <%= f.number_field :cambodian %>
  </div>
  <div class="field">
    <%= f.label :chinese %><br />
    <%= f.number_field :chinese %>
  </div>
  <div class="field">
    <%= f.label :filipino %><br />
    <%= f.number_field :filipino %>
  </div>
  <div class="field">
    <%= f.label :hmong %><br />
    <%= f.number_field :hmong %>
  </div>
  <div class="field">
    <%= f.label :indonesian %><br />
    <%= f.number_field :indonesian %>
  </div>
  <div class="field">
    <%= f.label :japanese %><br />
    <%= f.number_field :japanese %>
  </div>
  <div class="field">
    <%= f.label :korean %><br />
    <%= f.number_field :korean %>
  </div>
  <div class="field">
    <%= f.label :laotian %><br />
    <%= f.number_field :laotian %>
  </div>
  <div class="field">
    <%= f.label :malaysian %><br />
    <%= f.number_field :malaysian %>
  </div>
  <div class="field">
    <%= f.label :nepalese %><br />
    <%= f.number_field :nepalese %>
  </div>
  <div class="field">
    <%= f.label :pakistani %><br />
    <%= f.number_field :pakistani %>
  </div>
  <div class="field">
    <%= f.label :srilankan %><br />
    <%= f.number_field :srilankan %>
  </div>
  <div class="field">
    <%= f.label :taiwanese %><br />
    <%= f.number_field :taiwanese %>
  </div>
  <div class="field">
    <%= f.label :thai %><br />
    <%= f.number_field :thai %>
  </div>
  <div class="field">
    <%= f.label :vietnamese %><br />
    <%= f.number_field :vietnamese %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/races/edit.html.erb
<h1>Editing race</h1>

<%= render 'form' %>

<%= link_to 'Show', @race %> |
<%= link_to 'Back', races_path %>

app/views/races/index.html.erb
<h1>Listing races</h1>

<table>
  <tr>
    <th>County ID</th>
    <th>County name</th>
    <th>Year</th>
    <th>Indian</th>
    <th>Bangladeshi</th>
    <th>Bhutanese</th>
    <th>Cambodian</th>
    <th>Chinese</th>
    <th>Filipino</th>
    <th>Hmong</th>
    <th>Indonesian</th>
    <th>Japanese</th>
    <th>Korean</th>
    <th>Laotian</th>
    <th>Malaysian</th>
    <th>Nepalese</th>
    <th>Pakistani</th>
    <th>Srilankan</th>
    <th>Taiwanese</th>
    <th>Thai</th>
    <th>Vietnamese</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @races.each do |race| %>
  <tr>
    <td><%= race.county.id %></td>
    <td nowrap><%= race.county.name %></td>
    <td><%= race.year %></td>
    <td><%= race.indian %></td>
    <td><%= race.bangladeshi %></td>
    <td><%= race.bhutanese %></td>
    <td><%= race.cambodian %></td>
    <td><%= race.chinese %></td>
    <td><%= race.filipino %></td>
    <td><%= race.hmong %></td>
    <td><%= race.indonesian %></td>
    <td><%= race.japanese %></td>
    <td><%= race.korean %></td>
    <td><%= race.laotian %></td>
    <td><%= race.malaysian %></td>
    <td><%= race.nepalese %></td>
    <td><%= race.pakistani %></td>
    <td><%= race.srilankan %></td>
    <td><%= race.taiwanese %></td>
    <td><%= race.thai %></td>
    <td><%= race.vietnamese %></td>
    <td><%= link_to 'Show', race %></td>
    <td><%= link_to 'Edit', edit_race_path(race) %></td>
    <td><%= link_to 'Destroy', race, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Race', new_race_path %>

app/views/races/new.html.erb
<h1>New race</h1>

<%= render 'form' %>

<%= link_to 'Back', races_path %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Year:</b>
  <%= @race.year %>
</p>

<p>
  <b>Indian:</b>
  <%= @race.indian %>
</p>

<p>
  <b>Bangladeshi:</b>
  <%= @race.bangladeshi %>
</p>

<p>
  <b>Bhutanese:</b>
  <%= @race.bhutanese %>
</p>

<p>
  <b>Cambodian:</b>
  <%= @race.cambodian %>
</p>

<p>
  <b>Chinese:</b>
  <%= @race.chinese %>
</p>

<p>
  <b>Filipino:</b>
  <%= @race.filipino %>
</p>

<p>
  <b>Hmong:</b>
  <%= @race.hmong %>
</p>

<p>
  <b>Indonesian:</b>
  <%= @race.indonesian %>
</p>

<p>
  <b>Japanese:</b>
  <%= @race.japanese %>
</p>

<p>
  <b>Korean:</b>
  <%= @race.korean %>
</p>

<p>
  <b>Laotian:</b>
  <%= @race.laotian %>
</p>

<p>
  <b>Malaysian:</b>
  <%= @race.malaysian %>
</p>

<p>
  <b>Nepalese:</b>
  <%= @race.nepalese %>
</p>

<p>
  <b>Pakistani:</b>
  <%= @race.pakistani %>
</p>

<p>
  <b>Srilankan:</b>
  <%= @race.srilankan %>
</p>

<p>
  <b>Taiwanese:</b>
  <%= @race.taiwanese %>
</p>

<p>
  <b>Thai:</b>
  <%= @race.thai %>
</p>

<p>
  <b>Vietnamese:</b>
  <%= @race.vietnamese %>
</p>


<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'Back', races_path %>