config/routes.rb
Wheretomigrate::Application.routes.draw do
  resources :transit_scores

  resources :crimes
  resources :cost_livings
  resources :races
  resources :jobs_cities
  resources :cities do
    collection do
      get 'search'
    end
  end
  resources :counties

  match 'race_bangladeshi' => "Races#race_bangladeshi"
  match 'race_bhutanese' => "Races#race_bhutanese"
  match 'race_burmese' => "Races#race_burmese"
  match 'race_cambodian' => "Races#race_cambodian"
  match 'race_chinese' => "Races#race_chinese"
  match 'race_filipino' => "Races#race_filipino"
  match 'race_hmong' => "Races#race_hmong"
  match 'race_indian' => "Races#race_indian"
  match 'race_indonesian' => "Races#race_indonesian"
  match 'race_japanese' => "Races#race_japanese"
  match 'race_korean' => "Races#race_korean"
  match 'race_laotian' => "Races#race_laotian"
  match 'race_malaysian' => "Races#race_malaysian"

  match 'race_nepalese' => "Races#race_nepalese"
  match 'race_pakistani' => "Races#race_pakistani"
  match 'race_srilankan' => "Races#race_srilankan"
  match 'race_taiwanese' => "Races#race_taiwanese"
  match 'race_thai' => "Races#race_thai"
  match 'race_vietnamese' => "Races#race_vietnamese"
  

  match 'test' => "Home#index"

  root :to => "static_pages#main"

end

app/models/crime.rb
class Crime < ActiveRecord::Base
  attr_accessible :state, :county, :violent, :murder, :forcible_rape, :robbery, :aggravated_assault, :property_crime, :burglary, :larcenytheft, :motor_vehicle_theft, :arson, :county_id, :lat, :lng, :total, :size
end

app/controllers/crimes_controller.rb
class CrimesController < ApplicationController
  # GET /crimes
  # GET /crimes.json
  def index
    @crimes = Crime.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @crimes }
    end
  end

  # GET /crimes/1
  # GET /crimes/1.json
  def show
    @crime = Crime.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @crime }
    end
  end

  # GET /crimes/new
  # GET /crimes/new.json
  def new
    @crime = Crime.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @crime }
    end
  end

  # GET /crimes/1/edit
  def edit
    @crime = Crime.find(params[:id])
  end

  # POST /crimes
  # POST /crimes.json
  def create
    @crime = Crime.new(params[:crime])

    respond_to do |format|
      if @crime.save
        format.html { redirect_to @crime, notice: 'Crime was successfully created.' }
        format.json { render json: @crime, status: :created, location: @crime }
      else
        format.html { render action: "new" }
        format.json { render json: @crime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /crimes/1
  # PUT /crimes/1.json
  def update
    @crime = Crime.find(params[:id])

    respond_to do |format|
      if @crime.update_attributes(params[:crime])
        format.html { redirect_to @crime, notice: 'Crime was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @crime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crimes/1
  # DELETE /crimes/1.json
  def destroy
    @crime = Crime.find(params[:id])
    @crime.destroy

    respond_to do |format|
      format.html { redirect_to crimes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/crimes_helper.rb
module CrimesHelper
end

app/views/crimes/_form.html.erb
<%= form_for(@crime) do |f| %>
  <% if @crime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crime.errors.count, "error") %> prohibited this crime from being saved:</h2>

      <ul>
      <% @crime.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city_id %><br />
    <%= f.number_field :city_id %>
  </div>
  <div class="field">
    <%= f.label :population %><br />
    <%= f.text_field :population %>
  </div>
  <div class="field">
    <%= f.label :total_law_enforcement_employees %><br />
    <%= f.number_field :total_law_enforcement_employees %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crimes/edit.html.erb
<h1>Editing crime</h1>

<%= render 'form' %>

<%= link_to 'Show', @crime %> |
<%= link_to 'Back', crimes_path %>

app/views/crimes/index.html.erb
<h1>Listing crimes</h1>

<table>
  <tr>
    <th>City</th>
    <th>Population</th>
    <th>Total law enforcement employees</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @crimes.each do |crime| %>
  <tr>
    <td><%= crime.city_id %></td>
    <td><%= crime.population %></td>
    <td><%= crime.total_law_enforcement_employees %></td>
    <td><%= link_to 'Show', crime %></td>
    <td><%= link_to 'Edit', edit_crime_path(crime) %></td>
    <td><%= link_to 'Destroy', crime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Crime', new_crime_path %>

app/views/crimes/new.html.erb
<h1>New crime</h1>

<%= render 'form' %>

<%= link_to 'Back', crimes_path %>

app/views/crimes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>City:</b>
  <%= @crime.city_id %>
</p>

<p>
  <b>Population:</b>
  <%= @crime.population %>
</p>

<p>
  <b>Total law enforcement employees:</b>
  <%= @crime.total_law_enforcement_employees %>
</p>


<%= link_to 'Edit', edit_crime_path(@crime) %> |
<%= link_to 'Back', crimes_path %>