config/routes.rb
Wheretomigrate::Application.routes.draw do
  resources :transit_scores

  resources :crimes
  resources :cost_livings
  resources :races
  resources :jobs_cities
  resources :cities do
    collection do
      get 'search'
    end
  end
  resources :counties

  match 'race_bangladeshi' => "Races#race_bangladeshi"
  match 'race_bhutanese' => "Races#race_bhutanese"
  match 'race_burmese' => "Races#race_burmese"
  match 'race_cambodian' => "Races#race_cambodian"
  match 'race_chinese' => "Races#race_chinese"
  match 'race_filipino' => "Races#race_filipino"
  match 'race_hmong' => "Races#race_hmong"
  match 'race_indian' => "Races#race_indian"
  match 'race_indonesian' => "Races#race_indonesian"
  match 'race_japanese' => "Races#race_japanese"
  match 'race_korean' => "Races#race_korean"
  match 'race_laotian' => "Races#race_laotian"
  match 'race_malaysian' => "Races#race_malaysian"

  match 'race_nepalese' => "Races#race_nepalese"
  match 'race_pakistani' => "Races#race_pakistani"
  match 'race_srilankan' => "Races#race_srilankan"
  match 'race_taiwanese' => "Races#race_taiwanese"
  match 'race_thai' => "Races#race_thai"
  match 'race_vietnamese' => "Races#race_vietnamese"
  

  match 'test' => "Home#index"

  root :to => "static_pages#main"

end

app/models/jobs_city.rb
class JobsCity < ActiveRecord::Base
  attr_accessible :cityname, :latitude, :longitude, :numberjobs, :population, :statename

	# Number of job openings per 1000 people
	def job_div_pop
		( numberjobs.to_f / population ) * 1000
	end

	# Return the maximum of job_div_pop
	def job_div_pop_max
		JobsCity.connection.select_all("SELECT MAX(CAST(#{self.numberjobs}*1000 AS float)/CAST(#{self.population} AS float)) FROM jobs_cities")
	end

	def as_json options={}
	 {
		 lat: latitude,
		 lng: longitude,
		 size: job_div_pop,
		 pop: population,
		 html: sprintf("<h2>%s,<small> %s</small></h2>" + 
		 		"<b>Job openings:</b> <big>%.2f</big> per thousand people", 
		 		cityname, statename, job_div_pop)
	 }
	end
end

app/controllers/jobs_cities_controller.rb
class JobsCitiesController < ApplicationController
  # GET /jobs_cities
  # GET /jobs_cities.json
  def index
    @jobs_cities = JobsCity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs_cities }
    end
  end

  # GET /jobs_cities/1
  # GET /jobs_cities/1.json
  def show
    @jobs_city = JobsCity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @jobs_city }
    end
  end

  # GET /jobs_cities/new
  # GET /jobs_cities/new.json
  def new
    @jobs_city = JobsCity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @jobs_city }
    end
  end

  # GET /jobs_cities/1/edit
  def edit
    @jobs_city = JobsCity.find(params[:id])
  end

  # POST /jobs_cities
  # POST /jobs_cities.json
  def create
    @jobs_city = JobsCity.new(params[:jobs_city])

    respond_to do |format|
      if @jobs_city.save
        format.html { redirect_to @jobs_city, notice: 'Jobs city was successfully created.' }
        format.json { render json: @jobs_city, status: :created, location: @jobs_city }
      else
        format.html { render action: "new" }
        format.json { render json: @jobs_city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs_cities/1
  # PUT /jobs_cities/1.json
  def update
    @jobs_city = JobsCity.find(params[:id])

    respond_to do |format|
      if @jobs_city.update_attributes(params[:jobs_city])
        format.html { redirect_to @jobs_city, notice: 'Jobs city was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @jobs_city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs_cities/1
  # DELETE /jobs_cities/1.json
  def destroy
    @jobs_city = JobsCity.find(params[:id])
    @jobs_city.destroy

    respond_to do |format|
      format.html { redirect_to jobs_cities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/jobs_cities_helper.rb
module JobsCitiesHelper
end

app/views/jobs_cities/_form.html.erb
<%= form_for(@jobs_city) do |f| %>
  <% if @jobs_city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jobs_city.errors.count, "error") %> prohibited this jobs_city from being saved:</h2>

      <ul>
      <% @jobs_city.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cityName %><br />
    <%= f.text_field :cityName %>
  </div>
  <div class="field">
    <%= f.label :stateName %><br />
    <%= f.text_field :stateName %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :population %><br />
    <%= f.number_field :population %>
  </div>
  <div class="field">
    <%= f.label :numberJobs %><br />
    <%= f.number_field :numberJobs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs_cities/edit.html.erb
<h1>Editing jobs_city</h1>

<%= render 'form' %>

<%= link_to 'Show', @jobs_city %> |
<%= link_to 'Back', jobs_cities_path %>

app/views/jobs_cities/index.html.erb
<h1>Listing jobs_cities</h1>

<table>
  <tr>
    <th>Cityname</th>
    <th>Statename</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Population</th>
    <th>Numberjobs</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobs_cities.each do |jobs_city| %>
  <tr>
    <td><%= jobs_city.cityName %></td>
    <td><%= jobs_city.stateName %></td>
    <td><%= jobs_city.latitude %></td>
    <td><%= jobs_city.longitude %></td>
    <td><%= jobs_city.population %></td>
    <td><%= jobs_city.numberJobs %></td>
    <td><%= link_to 'Show', jobs_city %></td>
    <td><%= link_to 'Edit', edit_jobs_city_path(jobs_city) %></td>
    <td><%= link_to 'Destroy', jobs_city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Jobs city', new_jobs_city_path %>

app/views/jobs_cities/new.html.erb
<h1>New jobs_city</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_cities_path %>

app/views/jobs_cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cityname:</b>
  <%= @jobs_city.cityName %>
</p>

<p>
  <b>Statename:</b>
  <%= @jobs_city.stateName %>
</p>

<p>
  <b>Latitude:</b>
  <%= @jobs_city.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @jobs_city.longitude %>
</p>

<p>
  <b>Population:</b>
  <%= @jobs_city.population %>
</p>

<p>
  <b>Numberjobs:</b>
  <%= @jobs_city.numberJobs %>
</p>


<%= link_to 'Edit', edit_jobs_city_path(@jobs_city) %> |
<%= link_to 'Back', jobs_cities_path %>