config/routes.rb
Wheretomigrate::Application.routes.draw do
  resources :transit_scores

  resources :crimes
  resources :cost_livings
  resources :races
  resources :jobs_cities
  resources :cities do
    collection do
      get 'search'
    end
  end
  resources :counties

  match 'race_bangladeshi' => "Races#race_bangladeshi"
  match 'race_bhutanese' => "Races#race_bhutanese"
  match 'race_burmese' => "Races#race_burmese"
  match 'race_cambodian' => "Races#race_cambodian"
  match 'race_chinese' => "Races#race_chinese"
  match 'race_filipino' => "Races#race_filipino"
  match 'race_hmong' => "Races#race_hmong"
  match 'race_indian' => "Races#race_indian"
  match 'race_indonesian' => "Races#race_indonesian"
  match 'race_japanese' => "Races#race_japanese"
  match 'race_korean' => "Races#race_korean"
  match 'race_laotian' => "Races#race_laotian"
  match 'race_malaysian' => "Races#race_malaysian"

  match 'race_nepalese' => "Races#race_nepalese"
  match 'race_pakistani' => "Races#race_pakistani"
  match 'race_srilankan' => "Races#race_srilankan"
  match 'race_taiwanese' => "Races#race_taiwanese"
  match 'race_thai' => "Races#race_thai"
  match 'race_vietnamese' => "Races#race_vietnamese"
  

  match 'test' => "Home#index"

  root :to => "static_pages#main"

end

app/models/transit_score.rb
class TransitScore < ActiveRecord::Base
	include ApplicationHelper

  attr_accessible :cityname, :latitude, :longitude, :statename, :transit_score

	def state_code
		convert_state_code(stateName)
	end

	def as_json options={}
	 {
		 lat: latitude,
		 lng: longitude,
		 size: transit_score,
		 html: sprintf("<h2>%s,<small> %s</small></h2>" +
		 		"<b>Public Transportation Score:</b> <big>%d</big>",
		 		cityname, statename, transit_score)
	 }
	end
end

app/controllers/transit_scores_controller.rb
class TransitScoresController < ApplicationController
  # GET /transit_scores
  # GET /transit_scores.json
  def index
    @transit_scores = TransitScore.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transit_scores }
    end
  end

  # GET /transit_scores/1
  # GET /transit_scores/1.json
  def show
    @transit_score = TransitScore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transit_score }
    end
  end

  # GET /transit_scores/new
  # GET /transit_scores/new.json
  def new
    @transit_score = TransitScore.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transit_score }
    end
  end

  # GET /transit_scores/1/edit
  def edit
    @transit_score = TransitScore.find(params[:id])
  end

  # POST /transit_scores
  # POST /transit_scores.json
  def create
    @transit_score = TransitScore.new(params[:transit_score])

    respond_to do |format|
      if @transit_score.save
        format.html { redirect_to @transit_score, notice: 'Transit score was successfully created.' }
        format.json { render json: @transit_score, status: :created, location: @transit_score }
      else
        format.html { render action: "new" }
        format.json { render json: @transit_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transit_scores/1
  # PUT /transit_scores/1.json
  def update
    @transit_score = TransitScore.find(params[:id])

    respond_to do |format|
      if @transit_score.update_attributes(params[:transit_score])
        format.html { redirect_to @transit_score, notice: 'Transit score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transit_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transit_scores/1
  # DELETE /transit_scores/1.json
  def destroy
    @transit_score = TransitScore.find(params[:id])
    @transit_score.destroy

    respond_to do |format|
      format.html { redirect_to transit_scores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/transit_scores_helper.rb
module TransitScoresHelper
end

app/views/transit_scores/_form.html.erb
<%= form_for(@transit_score) do |f| %>
  <% if @transit_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transit_score.errors.count, "error") %> prohibited this transit_score from being saved:</h2>

      <ul>
      <% @transit_score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cityName %><br />
    <%= f.text_field :cityName %>
  </div>
  <div class="field">
    <%= f.label :stateName %><br />
    <%= f.text_field :stateName %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :transit_score %><br />
    <%= f.text_field :transit_score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transit_scores/edit.html.erb
<h1>Editing transit_score</h1>

<%= render 'form' %>

<%= link_to 'Show', @transit_score %> |
<%= link_to 'Back', transit_scores_path %>

app/views/transit_scores/index.html.erb
<h1>Listing transit_scores</h1>

<table>
  <tr>
    <th>Cityname</th>
    <th>Statename</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Transit score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transit_scores.each do |transit_score| %>
  <tr>
    <td><%= transit_score.cityName %></td>
    <td><%= transit_score.stateName %></td>
    <td><%= transit_score.latitude %></td>
    <td><%= transit_score.longitude %></td>
    <td><%= transit_score.transit_score %></td>
    <td><%= link_to 'Show', transit_score %></td>
    <td><%= link_to 'Edit', edit_transit_score_path(transit_score) %></td>
    <td><%= link_to 'Destroy', transit_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transit score', new_transit_score_path %>

app/views/transit_scores/new.html.erb
<h1>New transit_score</h1>

<%= render 'form' %>

<%= link_to 'Back', transit_scores_path %>

app/views/transit_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cityname:</b>
  <%= @transit_score.cityName %>
</p>

<p>
  <b>Statename:</b>
  <%= @transit_score.stateName %>
</p>

<p>
  <b>Latitude:</b>
  <%= @transit_score.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @transit_score.longitude %>
</p>

<p>
  <b>Transit score:</b>
  <%= @transit_score.transit_score %>
</p>


<%= link_to 'Edit', edit_transit_score_path(@transit_score) %> |
<%= link_to 'Back', transit_scores_path %>